spring.application.name=user
spring.application.port=8080

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=dev

encryption.secret.key=1234567890123456

jwt.secret.key=65748393jehfkjdsafha7adsf7ads98f79ads8f
access.token.jwt.expiration.time=300000
refresh.token.jwt.expiration.time=86400000


